###
GET http://localhost:9000/sakila/ HTTP/1.1

###
POST http://localhost:9000/library HTTP/1.1
Content-Type: application/json

{
    "titulo": "hola",
    "autor": "como estas",
    "edicion": 1
}

###
DELETE http://localhost:9000/library/3 HTTP/1.1

###
PUT http://localhost:9000/library/6 HTTP/1.1
Content-Type: application/json

{
    "titulo": "El principito",
    "autor": "no tengo ni idea",
    "edicion": 1
}